/**
 * @file    rdnx_timer.h
 * @author  Software development team
 * @brief   API for hardware timers
 * @version 0.1
 * @date    2026-03-18
 */
#ifndef RDNX_TIMER_H
#define RDNX_TIMER_H

/* ============================================================================
 * Include Files
 * ==========================================================================*/

/* Standard includes. */
#include <stdbool.h> // for bool
#include <stddef.h>  // for size_t
#include <stdint.h>

/* Core includes. */
#include <rdnx_types.h>

#ifdef __cplusplus
extern "C"
{
#endif

/* ============================================================================
 * Public Type Declarations
 * ==========================================================================*/

/**
 * @brief Timer identifier
 *
 * @note For STM32 mapped to the TIM1..TIM14
 */
typedef enum rdnx_timer
{
    RDNX_TIMER_1 = 0,
    RDNX_TIMER_2,
    RDNX_TIMER_3,
    RDNX_TIMER_4,
    RDNX_TIMER_5,
    RDNX_TIMER_6,
    RDNX_TIMER_7,
    RDNX_TIMER_8,
    RDNX_TIMER_9,
    RDNX_TIMER_10,
    RDNX_TIMER_11,
    RDNX_TIMER_12,
    RDNX_TIMER_13,
    RDNX_TIMER_14,
    /** @brief Total count of timer identifiers */
    RDNX_TIMER_COUNT
} rdnx_timer_t;

/**
 * @brief Prototype for hardware timer callback functions
 *
 * These callback functions are called from interrupt context whenever the
 * timer's interrupt is generated.
 *
 * @param[in] timer Hardware timer identifier for the timer that generated the
 *                  interrupt
 */
typedef void (*rdnx_timerdev_cb)(rdnx_timer_t timer);

/**
 * @brief Hardware timer configuration
 */
typedef struct rdnx_timer_params
{
    /** @brief Hardware timer identifier */
    rdnx_timer_t timer;

    /**
     * @brief Timer period
     *
     * Some (not all) uses of hardware timers involve the use of an integer
     * counter.  The timer hardware increments the counter once for every tick
     * of the clock (whose frequency is typically determined by the #divider
     * parameter).
     *
     * When the counter increments to the *period* value, it is reset to zero
     * and an action is taken (e.g. generating an interrupt or sampling an
     * analog-to-digital conversion channel).  The specific action depends on
     * the hardware device being driven by the timer.
     *
     * The frequency, in Hz, at which the counter will reset (triggering its
     * action), for a timer whose tick frequency is controlled by the #divider
     * parameter, may be computed using the following formula:
     *
     * @f[
     *     frequency = \frac{clock}{divider \cdot period}
     * @f]
     *
     * Where *clock* is the module's clock frequency.
     */
    uint32_t period;

    /**
     * @brief Divider used to determine the timer's clock frequency
     *
     * Some (not all) uses of hardware timers involve the use of an integer
     * divider used to generate the hardware timer's tick frequency.  When it
     * is used, the timer's frequency is generated by dividing the RDNX
     * module's clock frequency by the divider value.
     *
     * The frequency, in Hz, may be computed using the following formula:
     *
     * @f[
     *     frequency = \frac{clock}{divider}
     * @f]
     *
     * Where *clock* is the RDNX module's clock frequency (40 MHz for ).
     */
    uint16_t divider;

    /**
     * @brief Callback function for hardware timer interrupts.
     *
     * This function is called from an interrupt context whenever a *basic*
     * (aka *standalone*) timer device's period elapses.
     */
    rdnx_timerdev_cb cb_isr;
} rdnx_timer_params_t;

/**
 * @brief Handle to an initialized hardware timer
 */
typedef struct rdnx_timer_struct *rdnx_timer_handle_t;

/**
 * @brief Create a basic hardware timer device
 *
 * This creates a *basic* timer device where an interrupt is periodically
 * generated, based on the timer's parameters.  The timer's callback function
 * is called (from an interrupt context) when the interrupt is generated.
 *
 * @param[in]  tmr_params Hardware timer configuration parameters
 * @param[out] tmr_handle Pointer to memory which, on success, will contain a
 *                        handle to the configured device.
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_init(const rdnx_timer_params_t *tmr_params, rdnx_timer_handle_t *tmr_handle);

/**
 * @brief Modify the period of a hardware timer device
 *
 * @param[in] handle Handle to the hardware timer device
 * @param[in] period The new value for the timer's period
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_set_period(rdnx_timer_handle_t handle, uint32_t period);

/**
 * @brief Get the interrupt frequency of a basic hardware timer device
 *
 * This function returns the frequency (in Hz) at which interrupts will be
 * generated for a basic timer device.
 *
 * @param[in]  handle    Handle to the hardware timer device
 * @param[out] frequency Pointer to memory which, on success, will contain the
 *                       timer's interrupt frequency.
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_get_frequency(rdnx_timer_handle_t handle, uint32_t *frequency);

/**
 * @brief Enable a basic hardware timer device
 *
 * Start a basic timer device, so it will begin to generate interrupts
 * according to its configured parameters.
 *
 * @param[in] handle Handle to the hardware timer device
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_enable(rdnx_timer_handle_t handle);

/**
 * @brief Disable a basic hardware timer device
 *
 * Stop a basic timer device, so its interrupts will no longer be generated.
 *
 * @param[in] handle Handle to the hardware timer device
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_disable(rdnx_timer_handle_t handle);

/**
 * @brief Set the hardware timer's counter value
 *
 * @param[in] handle  Handle to the hardware timer device
 * @param[in] counter The hardware timer counter value
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_set_counter(rdnx_timer_handle_t handle, uint32_t counter);

/**
 * @brief Get the hardware timer's counter value
 *
 * @param[in]  handle  Handle to the hardware timer device
 * @param[out] counter Pointer to memory which, on success, will contain the
 *                     timer's counter value
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_get_counter(rdnx_timer_handle_t handle, uint32_t *counter);

/**
 * @brief Register callback function for hardware timer interrupts.
 *
 * This function is called from an interrupt context whenever a *basic*
 * (aka *standalone*) timer device's period elapses.
 *
 * @param[in]  handle  Handle to the hardware timer device
 * @param[in]  cb      Callback function
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_register_callback(rdnx_timer_handle_t handle, rdnx_timerdev_cb cb);

/**
 * @brief Unregister callback function for hardware timer interrupts.
 *
 * @param[in]  handle  Handle to the hardware timer device
 *
 * @return #RDNX_ERR_OK on success
 */
rdnx_err_t rdnx_timer_unregister_callback(rdnx_timer_handle_t handle);

#ifdef __cplusplus
}
#endif

#endif // RDNX_TIMER_H
